#!/bin/bash
TERM_WIDTH=($(tput cols))
if [[ ${TERM_WIDTH} -ge 120 ]]; then
  MENU_WIDTH=($((${TERM_WIDTH} / 2 )))
else
  MENU_WIDTH=${TERM_WIDTH}
fi
## poolController ##
## _poolcontroller_addr ##
_poolcontroller_addr() {
JSON_ENTRY="appAddress"
JSON_DESCRIP=("The address on the serial bus that this app will use.
The pumps don't seem to care what number you use.
Intellitouch won't respond unless this address is one of 32, 33, 34.
")
  printf "\033[31;4m${JSON_ENTRY} \033[32;24m\n${JSON_DESCRIP}\033[00m\n"
  awk -v s=${MENU_WIDTH} 'BEGIN {
    for(c=0;c<s;c++)
    printf "\033[7m="
    printf "\033[0m \n"
  }'
}

_poolcontroller_http() {
JSON_ENTRY="http"
JSON_DESCRIP=("enabled:
  1 for yes
  0 for no
expressPort:
  set to the value that you want the web pages to be served to.
  3000 = http://localhost:3000
redirectToHttps:
  1 for yes
  0 for no
  If this is 1, all other options except for the port will be ignored.
expressAuth:
  0 for no username/password.
  1 for username/password.
expressAuthFile :
  input the path to the file. 
  By default, /users.htpasswd.
  If you have expressAuth=1 then create the file users.htpasswd in the root of the application. 
  Use a tool such as http://www.htaccesstools.com/htpasswd-generator/ and paste your user(s) into this file.
  You will now be prompted for authentication."
  )
  printf "\033[31;4m${JSON_ENTRY} \033[32;24m\n${JSON_DESCRIP}\033[00m\n"
  awk -v s=${MENU_WIDTH} 'BEGIN {
    for(c=0;c<s;c++)
    printf "\033[7m="
    printf "\033[0m \n"
  }'
}
awk -v s=${MENU_WIDTH} 'BEGIN {
    for(c=0;c<s;c++)
    printf "\033[7m="
    printf "\033[0m \n"
  }'
_poolcontroller_addr
_poolcontroller_http